#ifndef EVENTS_H
#define EVENTS_H

#include <stdint.h>

// === EVENT DEFINITIONS (SYSTEM MESSAGING) ===

// This file defines all events and commands used for communication between different tasks in the system.

// Architecture Role:
// Sensors / MQTT / Web → Events → FSM → Commands → Actuators
// By standardizing events, the system achieves:
// - Loose coupling between modules
// - Clear and maintainable logic
// - Easy scalability

// === EVENT TYPES (INPUT TO FSM) ===

// These events are generated by:
// - Sensors (IR, ultrasonic, water)
// - Actuators (servo feedback)
// - External interfaces (MQTT, Web UI)

// They are sent to the FSM via a FreeRTOS queue.

typedef enum {

    // --- USER INTERACTION ---
    EVENT_HAND_DETECTED = 0,   // IR sensor: hand detected near bin
    EVENT_HAND_REMOVED,        // IR sensor: hand moved away

    // --- SENSOR UPDATES ---
    EVENT_DISTANCE_UPDATED,    // Ultrasonic measurement updated
    EVENT_BIN_FULL_DETECTED,   // Bin reached full threshold
    EVENT_BIN_EMPTIED,         // Bin emptied (fill level dropped)
    EVENT_WATER_DETECTED,      // Water/leak detected inside bin

    // --- ACTUATOR FEEDBACK ---
    EVENT_SERVO_OPEN_DONE,     // Servo finished opening lid
    EVENT_SERVO_CLOSE_DONE,    // Servo finished closing lid

    // --- TIME-BASED EVENTS ---
    EVENT_OPEN_TIMEOUT,        // Lid open timeout 

    // --- MANUAL CONTROL (MQTT / WEB) ---
    EVENT_MANUAL_OPEN,         // User requested lid open
    EVENT_MANUAL_CLOSE,        // User requested lid close

    // --- ALARM CONTROL ---
    EVENT_ALARM_ON,            // Enable alarm system
    EVENT_ALARM_OFF,           // Disable alarm system

    // --- BUZZER DIRECT CONTROL ---
    EVENT_BUZZER_ON,           // Turn buzzer ON manually
    EVENT_BUZZER_OFF           // Turn buzzer OFF manually

} dustbin_event_type_t;

// === EVENT STRUCTURE ===
typedef struct {
    dustbin_event_type_t type;  // Type of event
    uint32_t timestamp_ms;      // Time of occurrence (milliseconds)
} dustbin_event_t;

// === SERVO COMMANDS (FSM → SERVO TASK) ===
// These commands are sent from FSM to the servo task via a FreeRTOS queue.

typedef enum {
    SERVO_CMD_OPEN = 1,   // Open the lid
    SERVO_CMD_CLOSE = 2   // Close the lid
} servo_cmd_t;

// === BUZZER COMMANDS (FSM → BUZZER TASK) ===
// Defines different modes of buzzer operation.
typedef enum {

    BUZZER_CMD_OFF = 0,     // Turn buzzer OFF
    BUZZER_CMD_ON,          // Turn buzzer ON 

    // Alert modes (used for bin full)
    BUZZER_CMD_ALERT_ON,    // Start alert pattern (e.g., beeping)
    BUZZER_CMD_ALERT_OFF    // Stop alert pattern

} buzzer_cmd_t;

// === END OF FILE ===

#endif